### ISSUE TITLE
Website seems to be down. 

### ISSUE THREAD

**Issue by DanBeast1337** [JicuNull/MCReverse#6]
Well, really simple issue. Just says

_error: could not connect to host_

Probably an easy fix. ;)

**Comment by Louuke** [comment]
Hey, glad to see you are still with us :)

In fact, it's not going to be an easy fix and will take some time.
The API has changed at a point that is extremely difficult to reconstruct.

So yeah, it sucks.

**Comment by DanBeast1337** [comment]
Oh that's unfortunate. 

Thanks for putting in the effort though for keeping it up (hopefully!)

**Comment by Louuke** [comment]
There is now a new experimental version of McCoupon online. Hopefully nothing crashes in the next minutes and hours.

**Comment by QualmOnAcid** [comment]
would you be willing to release the fixed source code? ty

**Comment by Louuke** [comment]
Fortunately, the last few days everything is going well and the problem is solved for now. The current lack of 1€ vouchers is another bug that I will address soon.

> would you be willing to release the fixed source code? ty

The current fix does not consist of a single code snippet, but has required a lot of changes to McCoupon's codebase. Since the code of McCoupon itself is not public, I will not give further explanations here. However, in the [McBase ](https://github.com/JicuNull/MCReverse/blob/dev/src/main/java/icu/jnet/mcd/api/McBase.java)class of McReverse you can see which requests need a sensor token and which do not. I think that should already help.
